### PR TITLE
Review of event handlers, new window event listeners and RdWindowEvent class

### LINKED ISSUE #81: SDL window is unresponsive to usual closing events other than pressing "Esc"
https://github.com/asrob-uc3m/robotDevastation/issues/70#issuecomment-262845721
> For some reason I'm unable to close the window, not even by right-clicking on the Unity tile and selecting Quit. Does it work for you?

https://github.com/asrob-uc3m/robotDevastation/issues/70#issuecomment-262985229
> I cannot close the window either, I can only finish the program by pressing the ESC key. It might just be that SDL2 requires us to bind the event to some function (...)

### PR DESCRIPTION
**Pull request by PeterBowman**
Resolves #81. Includes:

* New `rd::RdWindowEvent` class. For now, it only supports `WINDOW_CLOSE` events.
* New `rd::RdInputEventListener::onWindowEvent` method, its implementation in several listener subclasses and invocation in `rd::RdSDLInputManager::inputCallback`.
* New `rd::MockupInputManager::sendWindowEvent` method.
* Deletion of `rd::MockupKey`; its constructors have been pulled up to `rd::RdKey`, which is now intended to be a sealed concrete class. Same applies to `rd::RdWindowEvent`.
* `rd::RdSDLKey` has been repurposed as a simple factory class and its sole role is to create a `rd::RdKey` object from a `SDL_Keycode`. Same applies to `rd::RdSDLWindowEvent` and `SDL_WindowEvent`.
* New `rd::InitState::EXIT_REQUESTED` condition to allow closing the game from its initial state.
* `rd::InitState` listens now to *Escape* key presses and consecutively closes the game.
* New tests:
  * `InitStateGoesToExit` in `testInitState.cpp`
  * `WindowEventSentAndReceivedCorrectly` in `testMockupInputManager.cpp `
* Miscellanea:
  * `rd::RdKey` objects are now passed by const reference as function parameters.
  * If possible, converting constructors are used to create `rd::RdKey` and `rd::RdWindowEvent` instances.
  * Got rid of pointers and dynamic memory management in `rd::RdSDLInputManager::inputCallback`.

Not done yet/proposed:

* Test cases for window events. So far, this has been done in `testMockupInputManager.cpp` and `testRdInputManager.cpp`. It could be done for `testGameState.cpp` et al. by simply replacing `sendKeyPress(RdKey::KEY_ESCAPE);` with `sendWindowEvent(RdWindowEvent::WINDOW_CLOSE);`, but feels a bit like code bloating as it's essentially the same test with a tiny change in the event type being invoked.
* `rd::RdSDLKey` and `rd::RdSDLWindowEvent` factory methods may fit better in a single class, say `RdSDLEventFactory`. Might not be the best idea due to separation of concerns (I find it quite attractive, though).

### CODE REVIEW

**Comment by David-Estevez** [comment]
Great job! Thanks,  @PeterBowman !!

**Comment by jgvictores** [comment]
@PeterBowman Bravísimo!

**Comment by PeterBowman** [comment]
@David-Estevez please take a look at the two commits referenced above. These address both "not done yet/proposed" tasks mentioned in this PR's description.

**Comment by David-Estevez** [comment]
Everythings seems ok!

**Pull request merged**
